/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as InternshipsIndexRouteImport } from './routes/internships/index'
import { Route as InternshipsIdRouteImport } from './routes/internships/$id'
import { Route as AuthenticatedInternshipsNewRouteImport } from './routes/_authenticated/internships/new'
import { Route as AuthenticatedInternshipsIdApplicantsRouteImport } from './routes/_authenticated/internships/$id/applicants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/internships/',
  path: '/internships/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsIdRoute = InternshipsIdRouteImport.update({
  id: '/internships/$id',
  path: '/internships/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInternshipsNewRoute =
  AuthenticatedInternshipsNewRouteImport.update({
    id: '/internships/new',
    path: '/internships/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternshipsIdApplicantsRoute =
  AuthenticatedInternshipsIdApplicantsRouteImport.update({
    id: '/internships/$id/applicants',
    path: '/internships/$id/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/internships/': typeof InternshipsIndexRoute
  '/internships/new': typeof AuthenticatedInternshipsNewRoute
  '/internships/$id/applicants': typeof AuthenticatedInternshipsIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/internships': typeof InternshipsIndexRoute
  '/internships/new': typeof AuthenticatedInternshipsNewRoute
  '/internships/$id/applicants': typeof AuthenticatedInternshipsIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/internships/': typeof InternshipsIndexRoute
  '/_authenticated/internships/new': typeof AuthenticatedInternshipsNewRoute
  '/_authenticated/internships/$id/applicants': typeof AuthenticatedInternshipsIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/internships/$id'
    | '/internships/'
    | '/internships/new'
    | '/internships/$id/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/internships/$id'
    | '/internships'
    | '/internships/new'
    | '/internships/$id/applicants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/internships/$id'
    | '/internships/'
    | '/_authenticated/internships/new'
    | '/_authenticated/internships/$id/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InternshipsIdRoute: typeof InternshipsIdRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/internships/': {
      id: '/internships/'
      path: '/internships'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/$id': {
      id: '/internships/$id'
      path: '/internships/$id'
      fullPath: '/internships/$id'
      preLoaderRoute: typeof InternshipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/internships/new': {
      id: '/_authenticated/internships/new'
      path: '/internships/new'
      fullPath: '/internships/new'
      preLoaderRoute: typeof AuthenticatedInternshipsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internships/$id/applicants': {
      id: '/_authenticated/internships/$id/applicants'
      path: '/internships/$id/applicants'
      fullPath: '/internships/$id/applicants'
      preLoaderRoute: typeof AuthenticatedInternshipsIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedInternshipsNewRoute: typeof AuthenticatedInternshipsNewRoute
  AuthenticatedInternshipsIdApplicantsRoute: typeof AuthenticatedInternshipsIdApplicantsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedInternshipsNewRoute: AuthenticatedInternshipsNewRoute,
  AuthenticatedInternshipsIdApplicantsRoute:
    AuthenticatedInternshipsIdApplicantsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InternshipsIdRoute: InternshipsIdRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
